-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 08:34:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbhelpdesk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbhelpdesk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbhelpdesk` DEFAULT CHARACTER SET utf8mb4 ;
USE `dbhelpdesk` ;

-- -----------------------------------------------------
-- Table `dbhelpdesk`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhelpdesk`.`categorias` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(512) NOT NULL,
  `descripcion` VARCHAR(1024) NULL DEFAULT NULL,
  `activo` TINYINT(4) NULL DEFAULT NULL,
  `borrado` TINYINT(4) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbhelpdesk`.`tipousers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhelpdesk`.`tipousers` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(64) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `nivel` INT(11) NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_name_guard_name_unique` (`nombre` ASC, `descripcion` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbhelpdesk`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhelpdesk`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(512) NULL,
  `name` VARCHAR(64) NULL,
  `email` VARCHAR(128) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `tipouser_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_tipo_users1_idx` (`tipouser_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_tipo_users1`
    FOREIGN KEY (`tipouser_id`)
    REFERENCES `dbhelpdesk`.`tipousers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbhelpdesk`.`incidencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhelpdesk`.`incidencias` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `motivo` TEXT NULL DEFAULT NULL,
  `detalle` TEXT NULL DEFAULT NULL,
  `fecincidencia` DATETIME NULL DEFAULT NULL,
  `estado` TINYINT(4) NULL DEFAULT NULL,
  `prioridad` TINYINT(4) NULL DEFAULT NULL,
  `oficina` TEXT NULL,
  `activo` TINYINT(4) NULL DEFAULT NULL,
  `borrado` TINYINT(4) NULL DEFAULT NULL,
  `categoria_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `incidencias_categoria_id_foreign` (`categoria_id` ASC) VISIBLE,
  INDEX `incidencias_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `incidencias_categoria_id_foreign`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `dbhelpdesk`.`categorias` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `incidencias_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `dbhelpdesk`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbhelpdesk`.`solucions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhelpdesk`.`solucions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `detalle` TEXT NOT NULL,
  `fecsolucion` DATETIME NOT NULL,
  `activo` TINYINT(4) NULL DEFAULT NULL,
  `borrado` TINYINT(4) NULL DEFAULT NULL,
  `incidencia_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `solucions_incidencia_id_foreign` (`incidencia_id` ASC) VISIBLE,
  INDEX `solucions_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `solucions_incidencia_id_foreign`
    FOREIGN KEY (`incidencia_id`)
    REFERENCES `dbhelpdesk`.`incidencias` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `solucions_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `dbhelpdesk`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbhelpdesk`.`responsables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhelpdesk`.`responsables` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(128) NOT NULL,
  `cargo` VARCHAR(45) NULL,
  `activo` TINYINT(4) NOT NULL,
  `borrado` TINYINT(4) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbhelpdesk`.`categorias_responsables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhelpdesk`.`categorias_responsables` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `categoria_id` BIGINT(20) UNSIGNED NOT NULL,
  `responsable_id` BIGINT(20) NOT NULL,
  INDEX `fk_categorias_responsables_categorias1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_categorias_responsables_responsables1_idx` (`responsable_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_categorias_responsables_categorias1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `dbhelpdesk`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorias_responsables_responsables1`
    FOREIGN KEY (`responsable_id`)
    REFERENCES `dbhelpdesk`.`responsables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbhelpdesk`.`oficinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhelpdesk`.`oficinas` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `oficina` VARCHAR(512) NOT NULL,
  `descripcion` TEXT NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
